# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vidya Sagar M.A.V"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mavuduru.123.sagar@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 9676231598"
resume_contact_address:         "Srikakulam, Andhra Pradesh, India"

resume_header_contact_info:     "Srikakulam, Andhra Pradesh, India • 532445 • mavuduru.123.sagar@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced software developer specializing in Flutter with 3 years of expertise. Skilled in ReactJS, NodeJS, and Python, passionate about AI and machine learning. Known for enhancing user experiences and optimizing backend processes to deliver innovative app solutions.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/vidya-hub"
  resume_linkedin_url:          "https://www.linkedin.com/in/vidya-sagar-129b17130"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://vidya-hub.github.io/resume/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
